### ISSUE TITLE
Presets props are sent to the API, which are not sent by the official UI.

### ISSUE THREAD

**Issue by Fensterbank** [arthus-leroy/novelai-api#23]
While debugging my requests against the API and comparing it with the ones from the WebUI, I noticed something weird.
My first thought was that the presets files are outdated, but indeed they do match the ones I can export from the Web UI.

The following properties in red are part of the preset files, but the Web UI does not send them to the API, while this library does.
![grafik](https://github.com/Aedial/novelai-api/assets/1684826/c8728a37-2522-4452-b1a6-3f1e688a0531)

I don't know, if this affects the generation (because I seem to have other issues atm) or if the API ignores them, but I think we should make sure our requests matches them from the official Web UI.

**Comment by Aedial** [comment]
These values are default values, they do not affect the generation because :
1. Their value put them in a "disabled" state (does nothing)
2. Their behavior should be disabled when they are not part of the preset by not being in the 'order' parameter.

One thing that could be done is filtering out parameters that are not part of enabled sampling methods (not in 'order'), which is what the website does.

**Comment by MelonWang9527** [comment]
If you're using Anime_v3 model, different default settings between the website and this repo are:

- the website default uses k_euler sampler with scale 5
- this repo uses k_euler_ancestral sampler with scale 11

This can affect the result, remember to set the sampler if needed.

**Comment by Aedial** [comment]
All 3 models use different default configuration, the current default is more a holdover from v1 than anything. It feels awkward to change these default at each new version, considering any model can be used with an ImagePreset; rather I want people to customize their configuration (even more so there is no official settings preset in image gen).
One thing I could do, however, is make a factory function that would build the ImagePreset from the defaults of the chosen model, and remove the defaults.

"Explicit is better than implicit."
\- Zen of Python
