### ISSUE TITLE
ddim sampler using /ai/generation-image API not working properly on nai-diffusion-v3.

### ISSUE THREAD

**Issue by bedovyy** [arthus-leroy/novelai-api#26]
If sampler set to ddim for `/ai/generation-image` with `nai-diffusion-v3`, it generates noised image.

![using_API](https://github.com/Aedial/novelai-api/assets/137917911/dcc3977b-4671-4965-9665-b9a9c08eac01)

On web page, it generates properly. but in EXIF, sampler shows as "Euler a" on parameters and "ddim_v3" on Comment.

![using_WEB](https://github.com/Aedial/novelai-api/assets/137917911/6d110c75-8155-4f4c-9b99-b1fbe65ddb42)

It seems using ddim sampler via API needs more settings or something, but I cannot get additional settings or params for ddim from code.

I checked,
- Euler a sampler generates different image.

I didn't check,
- sending sampler as "ddim_v3".
- sending "ddim" with other models.

By the way, on web page, if SMEA+DYN is checked with other sampler then change sampler to DDIM,
the generation costs 28 anlas, not 20 anlas even though DDIM cannot use SMEA or SMEA+DYN.

**Comment by Aedial** [comment]
It seems the website seamlessly translates ddim to ddim_v3 with v3. I recall ddim being somewhat broken for older versions, which might explain it. Pushing a fix for that tomorrow.
For SMEA and DYN, there is no check in my cost calculation for whether or not a combination is possible. It's complicated to maintain and not that meaningful. For v3, SMEA and SMEA+DYN are simply multipliers on the cost. On v1 and v2, it's more complicated.

**Comment by Aedial** [comment]
Fixed with 0f62c89c1fde1f50fb422a2886d1ed0320f22f4f

**Comment by bedovyy** [comment]
I could generate same image as web.
Thank you.
