### ISSUE TITLE
What's the format for inpainting masks?

### ISSUE THREAD

**Issue by hollowstrawberry** [arthus-leroy/novelai-api#27]
I can't figure it out. Whatever I do it just seems to inpaint random parts of the image and ignore my prompt. txt2img and img2img works fine.

**Comment by Aedial** [comment]
The inpainting mask uses a black and white png image like that, encoded in base 64 :
![inpainting_mask](https://github.com/Aedial/novelai-api/assets/38740785/c1ddf8b8-4be6-4703-81ac-37f774cc4eca)
As said [here](https://github.com/Aedial/novelai-api/blob/59bb0ea417c79ac589d97e350c401f36575da2fb/novelai_api/ImagePreset.py#L250C6-L250C6)

**Comment by hollowstrawberry** [comment]
I think the mask is 1/8 the original size, since it wasn't behaving correctly when I tried yesterday in full size
