### ISSUE TITLE
Dependency package `sentencepiece (==0.1.99)` dont support `python==3.12`

### ISSUE THREAD

**Issue by CherryGS** [arthus-leroy/novelai-api#29]
Until `sentencepiece == 0.2` , it started supporting `python==3.12`
from pypi
![image](https://github.com/Aedial/novelai-api/assets/61844819/fb71a560-b616-4f6c-ad8f-bbbb2fd7eb57)

**Comment by Aedial** [comment]
Oh, this issue is completed with b690a4eaf6c6d41aeaeedd65c19bf5799e4a41ba.
Forgot to take care of it.
