### ISSUE TITLE
random tags

### ISSUE THREAD

**Issue by TimmekHW** [arthus-leroy/novelai-api#30]
I want to use random nai tags. What is their endpoint?

**Comment by Aedial** [comment]
You mean the random prompt button? There is no endpoint, it's a function that creates the prompt in your internet browser with a list of tags, weights

**Comment by TimmekHW** [comment]
> Вы имеете в виду кнопку случайной подсказки? Конечной точки нет, это функция, которая создает в вашем интернет-браузере приглашение со списком тегов и весов.

how can I repeat it? I love Stable Diffusion and I like the tags that nai makes. 
how can it be done for automatic1111

**Comment by Aedial** [comment]
You will need to reverse engineer the Javascript code. It's not complicated, just tedious.

**Comment by TimmekHW** [comment]
> You will need to reverse engineer the Javascript code. It's not complicated, just tedious.


is there a source code or an extension? maybe documentation?

**Comment by sudoskys** [comment]
@TimmekHW I reimplemented [random_prompt](https://github.com/LlmKira/novelai-python/tree/main/src/novelai_python/tool/random_prompt) in Python.
