### ISSUE TITLE
default.preset does not apply.

### ISSUE THREAD

**Issue by Victini00** [arthus-leroy/novelai-api#33]
`preset = ImagePreset.from_v3_config()`
(from generate_image_test_samplers.py)

`return cls.from_file(Path(__file__).parent / "image_presets" / "presets_v3" / "default.preset")`
(from ImagePreset.py)

So I modified novelai_api/image_presets/presets_v3/default.preset, but it does not apply. I've tried reinstalling the module, but still does not works.

**Comment by Aedial** [comment]
Hm. What are you trying to do?
If you want to change a parameter, you can simply set it.
If you want to load a custom preset, you can just from_file().

**Comment by Victini00** [comment]
I want to change parameters(for example,
"sampler": "k_dpmpp_2s_ancestral",
"steps": 28 -> 40
"n_samples": 1 
"strength": 0.7 -> 0.9...
)
even I fixed default.preset file, but changes do not apply.

**Comment by Aedial** [comment]
I would recommend you take a look at [generate_image.py](https://github.com/Aedial/novelai-api/blob/main/example/generate_image.py). "default" is there to be the default settings, from which you can change parameters using the intended way.

**Comment by Victini00** [comment]
It worked as i intended, thanks!
