### ISSUE TITLE
They have two different base64

### ISSUE THREAD

**Issue by zhulinyv** [arthus-leroy/novelai-api#34]
The base64 obtained through encode is not consistent with that generated by NovelAI.

https://github.com/Aedial/novelai-api/blob/2174602d346152d38ce2b43fcec8c9666a72f89a/example/generate_image_with_img2img.py#L25

Even though I have the same generation parameters, the generated images are different with using the NovelAI web page.

**Comment by Aedial** [comment]
I see no issue on my side. The image I get from the website and from the API are the same. Make sure you chose the right model and understand the [defaults](https://github.com/Aedial/novelai-api/tree/main/novelai_api/image_presets), including things like UC and quality toggle, and overwrite them if not.
If you are talking purely on the b64 encoding of the 2 images, of course it will be different, as the signed hash and the generation time will be different for any 2 generations.
Looking at the metadata, there is no difference beside these two.

Feel free to re-open the ticket if you want to add missing information.
