### ISSUE TITLE
Unable to log in with email and password

### ISSUE THREAD

**Issue by Awakumori** [arthus-leroy/novelai-api#36]
Hello,

I tried logging in with my email and password, and it worked successfully when I used python -m novelai_api access_key. However, when I used the same email and password with python -m novelai_api access_token, it always failed, returning the error novelai_api.NovelAIError.NovelAIError: https://api.novelai.net/user/login (401) - Incorrect access key.

This confuses me a lot: I used the same email and password, but got completely different results.

Please check the image attached.

![2024-09-01 011107](https://github.com/user-attachments/assets/b70aa097-1e06-473d-be7f-2bd866fb7cb7)

![2024-09-01 011204](https://github.com/user-attachments/assets/917698ce-7d95-4ab4-bc63-0d9da7d6f62d)

**Comment by Aedial** [comment]
So, there are 2 things : access key and access token.
- The key is derived from your username (email address) and password. It is the key to your account, but you can only use it to get an access token. 
- The token is a limited time (30 days) pass to using your account. It is used for any actions sent to the server.

As such, you need to get the access key then use the login endpoint to get the access token from the access key (see https://github.com/Aedial/novelai-api/blob/main/novelai_api/_high_level.py#L61). From what I can see, you're trying to use your email to get the access token.

**Comment by Awakumori** [comment]
Thank you for your reply.
In your reply, you pointed out that I should not use email to get the access token.
However, I followed the instructions in the README file. According to the README file, getting the access token and getting the access key use the same parameters, i.e. [username,password].
Please check the image.
![2024-09-03 010541](https://github.com/user-attachments/assets/2966692b-e4b1-4411-a3cb-a058dad0d31c)
![2024-09-03 010557](https://github.com/user-attachments/assets/86fef8f1-fc12-40c7-8ea3-9b0fd3942da3)

**Comment by Aedial** [comment]
Yes, indeed. Been a while I used these and I forgot. It's indeed login and password.

If your password contains special characters (like '\'), you might need to escape them, because of the terminal. This is, however, not an issue when calling the login from code itself, it's a terminal quirk.
