### ISSUE TITLE
Please add text generate to examples

### ISSUE THREAD

**Issue by ghost** [arthus-leroy/novelai-api#6]

**Comment by Aedial** [comment]
The test tests/test_generate.py currently acts as the text generation example (as said in the README), due to the sheer amount of examples required to cover everything. I agree it would be good to get some examples later on, but I need to reduce the boilerplate code of examples, first.

**Comment by Aedial** [comment]
Done with bd00e414824a9b3efd5f7e1dbbeaea8193798936
