### ISSUE TITLE
Please add proxy setting to connect api

### ISSUE THREAD

**Issue by zmdyy0318** [arthus-leroy/novelai-api#7]
My country access interface is very poor

**Comment by Aedial** [comment]
Hi, can you try with the proxy_impl branch ? Some helpers have been put in the generate_image.py example, and the aiohttp documentation on proxy should also help a lot: https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support.

**Comment by zmdyy0318** [comment]
I have tried connecting my own proxy service and he works fine

    # insert proxy address here
    api_inst.api.proxy = "http://127.0.0.1:7890"
    # insert proxy address auth here
    api_inst.api.proxy_auth = None

**Comment by Aedial** [comment]
Pushed onto the main branch with f5a44481430ff760deb7ed766c0c9a25c4bdd250
