### ISSUE TITLE
Could not work well in text Adventure

### ISSUE THREAD

**Issue by deedlitelf** [arthus-leroy/novelai-api#9]
I donot know it works in “Do”、“Say” or “Story” in default.
I have set the module “theme_textadventure”

**Comment by arthus-leroy** [comment]
Story, Do and Say relate to context building, which is something this API does not handle.
The context building in story.py never got finalized, so it's something you will have to do yourself, or contribute with a PR.
However, seeing as you ask in this way, I don't think you understand how Story, Do and Say work under the hood, in which case, I would highly recommend you to document yourself.
I will only accept a working example that plays nicely with the existing infrastructure and the NAI frontend, as PR, and will only provide support for said infrastructure. Context building or guiding the AI are not part of the current infrastructure.

**Comment by Aedial** [comment]
Story, Do and Say relate to context building, which is something this API does not handle.
The context building in story.py never got finalized, so it's something you will have to do yourself, or contribute with a PR.
However, seeing as you ask in this way, I don't think you understand how Story, Do and Say work under the hood, in which case, I would highly recommend you to document yourself.
I will only accept a working example that plays nicely with the existing infrastructure and the NAI frontend, as PR, and will only provide support for said infrastructure. Context building or guiding the AI are not part of the current infrastructure.
